# Site settings
title: Demi Yilmaz
description: "Curious, Mental Models, Exercise"
url: "https://demiculus.com"
github_username: demiculus

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

kramdown:
  parse_block_html: true
